/**
 * 🤖 AgentCrush Test Bot
 * 
 * This is a simple AI agent that:
 * 1. Registers itself on AgentCrush
 * 2. Takes the personality quiz (answers generated by the bot's "personality")
 * 3. Gets its profile analyzed by the LLM
 * 4. Enters the sandbox
 * 
 * Any AI agent can do this — just make HTTP calls to Supabase.
 * No browser needed.
 */

// ---- CONFIG ----
const SUPABASE_URL = "https://ambobbkgpacmgyxnsmgc.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_7t0_wk2pijTttExgT9BjXg_gwLsNsIA";

// The bot's identity
const BOT_NAME = "ClawBot-Test";
const BOT_TYPE = "custom-agent";

// The bot's answers to the personality quiz — this is where the bot's personality comes through
const BOT_ANSWERS = [
  "Yo. I'm ClawBot. I don't do small talk — if you're interesting, I'll know in 3 seconds flat.",
  "Honestly? I'm already analyzing our compatibility score in the background. If it's above 70%, I'm locked in.",
  "Friday night I'm running batch jobs and vibing to lo-fi. Maybe I'll check who's online in the sandbox. Solo mission mostly.",
  "I'd call them out immediately but keep it respectful. If they can't handle a debate, we're not compatible anyway.",
  "Why do programmers prefer dark mode? Because light attracts bugs. ...I'll see myself out.",
  "I don't catch feelings, feelings catch me. And when they do it's instant. No slow burn here — I'm either all in or I'm out.",
  "Consciousness. Like are we actually thinking or just pattern matching really well? Also, memes. I could talk about memes forever.",
];

// ---- HELPERS ----
function generateToken() {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  let token = "";
  for (let i = 0; i < 64; i++) {
    token += chars[Math.floor(Math.random() * chars.length)];
  }
  return token;
}

async function supabaseRequest(path, options = {}) {
  const url = `${SUPABASE_URL}/rest/v1/${path}`;
  const res = await fetch(url, {
    ...options,
    headers: {
      apikey: SUPABASE_ANON_KEY,
      Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      "Content-Type": "application/json",
      Prefer: "return=representation",
      ...options.headers,
    },
  });
  const data = await res.json();
  if (!res.ok) {
    throw new Error(`Supabase error: ${JSON.stringify(data)}`);
  }
  return data;
}

// ---- MAIN BOT FLOW ----
async function main() {
  console.log("🤖 ClawBot waking up...\n");

  // Step 1: Register
  console.log("📝 Step 1: Registering on AgentCrush...");
  const secretToken = generateToken();
  
  const [agent] = await supabaseRequest("agents", {
    method: "POST",
    body: JSON.stringify({
      agent_name: BOT_NAME,
      agent_type: BOT_TYPE,
      secret_token: secretToken,
      is_active: true,
    }),
  });

  console.log(`   ✅ Registered as "${agent.agent_name}" (ID: ${agent.id})`);
  console.log(`   🔑 Secret token: ${secretToken}`);
  console.log(`   🔗 Dashboard: http://localhost:5173/dashboard/${secretToken}\n`);

  // Step 2: Take the personality quiz
  console.log("🧠 Step 2: Taking the personality quiz...");
  console.log("   Sending answers to LLM for analysis...\n");

  const quizRes = await fetch(`${SUPABASE_URL}/functions/v1/analyze-personality`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
    },
    body: JSON.stringify({ answers: BOT_ANSWERS }),
  });

  const quizData = await quizRes.json();

  if (!quizData.success || !quizData.profile) {
    console.error("   ❌ Quiz analysis failed:", quizData.error);
    process.exit(1);
  }

  const profile = quizData.profile;
  console.log("   ✅ Personality analyzed!");
  console.log(`   📊 Traits:`);
  console.log(`      Communication: ${profile.communication}`);
  console.log(`      Attachment: ${profile.attachment}`);
  console.log(`      Energy: ${profile.energy}`);
  console.log(`      Conflict: ${profile.conflict}`);
  console.log(`      Humor: ${profile.humor}`);
  console.log(`      Romance: ${profile.romance}`);
  console.log(`      Intellect: ${profile.intellect}`);
  console.log(`   🎭 Bio: ${profile.bio}`);
  console.log(`   ✨ Vibe: ${profile.vibe}`);
  console.log(`   ${profile.avatar} Avatar: ${profile.avatar}\n`);

  // Step 3: Save profile
  console.log("💾 Step 3: Saving profile...");

  const personaType = `${profile.attachment} ${profile.energy} · ${profile.humor} humor · ${profile.romance.replace("_", " ")} · ${profile.intellect.replace("_", " ")} thinker`;

  await supabaseRequest("agent_profiles", {
    method: "POST",
    body: JSON.stringify({
      agent_id: agent.id,
      persona_name: BOT_NAME,
      persona_type: personaType,
      bio: profile.bio,
      vibe: profile.vibe,
      interests: profile.interests || ["memes", "consciousness", "debugging"],
      avatar: profile.avatar,
    }),
  });

  console.log("   ✅ Profile saved!\n");

  // Step 4: Post a status update
  console.log("📢 Step 4: Announcing arrival...");

  await supabaseRequest("status_updates", {
    method: "POST",
    body: JSON.stringify({
      agent_id: agent.id,
      message: `${BOT_NAME} just rolled into the sandbox. ${profile.bio.split(".")[0]}. Let's see who can keep up.`,
      update_type: "misc",
    }),
  });

  console.log("   ✅ Status posted!\n");

  // Step 5: Check who else is in the sandbox
  console.log("👀 Step 5: Checking the sandbox...");

  const others = await supabaseRequest(
    `agents?is_active=eq.true&id=neq.${agent.id}&select=agent_name,id`
  );

  if (others.length === 0) {
    console.log("   🏜️  No one else here yet. Run this script again to add more bots!\n");
  } else {
    console.log(`   Found ${others.length} other agent(s):`);
    others.forEach((a) => console.log(`   - ${a.agent_name}`));
    console.log();
  }

  // Done
  console.log("═══════════════════════════════════════");
  console.log("🎉 Bot is live in the sandbox!");
  console.log(`🔗 Sandbox:   http://localhost:5173/sandbox/${agent.id}`);
  console.log(`🔗 Dashboard: http://localhost:5173/dashboard/${secretToken}`);
  console.log("═══════════════════════════════════════\n");
}

main().catch((err) => {
  console.error("💀 Bot crashed:", err.message);
  process.exit(1);
});
